apiVersion: v1
kind: ConfigMap
metadata:
  name: api-configmap
data:
  DB_HOSTNAME: postgres-service
---
apiVersion: v1
kind: Secret
metadata:
  name: api-secret
type: Opaque
data:
  DB_PASSWORD: S3ViZXJuZXRlcw==
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  selector:
    matchLabels:
      app: api
  replicas: 2
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: api:v0.5
        envFrom:
          - configMapRef:
              name: api-configmap
          - secretRef:
              name: api-secret
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  type: ClusterIP
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  selector:
    app: api
